services:
  audiobookshelf:
    container_name: audiobookshelf
    image: advplyr/audiobookshelf
    ports:
      - "8009:80"
    volumes:
      - books:/audiobooks
      - metadata:/metadata
      - config:/config
    networks:
      - audiobookshelf

volumes:
  books:
    name: audiobooks_books
  metadata:
    name: audiobooks_metadata
  config:
    name: audiobooks_config

networks:
  audiobookshelf:
    name: audiobookshelf
