services:
  vaultwarden:
    image: "vaultwarden/server:latest"
    container_name: vaultwarden
    volumes:
      - data:/data/
    networks:
      - vaultwarden
    ports:
      - "8001:80"
    restart: unless-stopped

volumes:
  data:
    name: vaultwarden_data
networks:
  vaultwarden:
    name: vaultwarden
