services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9101:9090"
    volumes:
      - "prometheus:/etc/prometheus/"
    networks:
      grafana:
    depends_on:
      - node_exporter
      - cadvisor

  node_exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node_exporter
    command:
      - "--path.rootfs=/host"
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    networks:
      grafana:
    command:
      - "-housekeeping_interval=10s"
      - "-docker_only=true"
    devices:
      - /dev/kmsg:/dev/kmsg

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    networks:
      grafana:
    ports:
      - "3000:3000"
    volumes:
      - "grafana:/var/lib/grafana"
    depends_on:
      - prometheus

volumes:
  prometheus:
    name: prometheus
  grafana:
    name: grafana
networks:
  grafana:
    name: grafana
