services:
  jsWiki_db:
    image: postgres:11-alpine
    container_name: jsWiki_db
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - jsWiki

  jsWiki_web:
    image: ghcr.io/requarks/wiki:latest
    container_name: jsWiki_web
    depends_on:
      - jsWiki_db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "8008:3000"
    volumes:
      - content:/wiki/data/content
    networks:
      - jsWiki

volumes:
  data:
    name: jsWiki_db
  content:
    name: jsWiki_web

networks:
  jsWiki:
    name: jsWiki
